version: '3'

volumes:
  opennebula_db:
  opennebula_data:
  oneadmin_data:
  opennebula_nodedata:
  oneadmin_nodedata:

networks:
  onenet:
#    external: true

services:
  db:
    env_file:
      - .env
    image: mariadb:10
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
      MYSQL_DATABASE: "${MYSQL_DATABASE}"
      MYSQL_USER: "${MYSQL_USER}"
      MYSQL_PASSWORD: "${MYSQL_PASSWORD}"
    volumes:
      - opennebula_db:/var/lib/mysql
    networks:
      - onenet
    deploy:
      restart_policy:
        condition: always
        delay: 10s
      replicas: 1

  opennebula-frontend:
    env_file:
      - .env
    image: "opennebula-frontend:${OPENNEBULA_VERSION:-latest}"
    build:
      args:
        OPENNEBULA_VERSION: "${OPENNEBULA_VERSION}"
      context: "./opennebula-frontend/${ONEDOCKER_INIT:-systemd}/"
      dockerfile: "Dockerfile-${ONEDOCKER_OS:-centos}"
    restart: always
    privileged: true
    environment:
      OPENNEBULA_FRONTEND_SERVICE: "oned"
      OPENNEBULA_FRONTEND_HOSTNAME: "${OPENNEBULA_FRONTEND_HOSTNAME}"
      OPENNEBULA_FRONTEND_PUBLISHED_SSHPORT: "${OPENNEBULA_FRONTEND_PUBLISHED_SSHPORT:-2222}"
      OPENNEBULA_NODE_SSHPORT: "${OPENNEBULA_NODE_SSHPORT:-2222}"
      OPENNEBULA_NODE_HOSTNAME: "${OPENNEBULA_NODE_HOSTNAME}"
      ONEADMIN_PASSWORD: "${ONEADMIN_PASSWORD}"
      ONEADMIN_SSH_PRIVKEY: "/ssh/id_rsa"
      ONEADMIN_SSH_PUBKEY: "/ssh/id_rsa.pub"
      MYSQL_DATABASE: "${MYSQL_DATABASE}"
      MYSQL_USER: "${MYSQL_USER}"
      MYSQL_PASSWORD: "${MYSQL_PASSWORD}"
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
    depends_on:
      - db
      - opennebula-node
    ports:
      - "${OPENNEBULA_FRONTEND_PUBLISHED_SSHPORT:-2222}:22"
      - "2633:2633"
    volumes:
      - opennebula_data:/data
      - oneadmin_data:/oneadmin
      - /var/run/docker.sock:/var/run/docker.sock
      - ./ssh:/ssh:ro
    tmpfs:
      - /run
      - /run/lock
      - /tmp
      - /var/tmp
      - /var/lib/containers
      - /var/lib/docker
#      - /sys/fs/cgroup/systemd
#      - /var/lib/journal
    networks:
      - onenet
    deploy:
      restart_policy:
        condition: always
        delay: 10s
      replicas: 1

  opennebula-sunstone:
    env_file:
      - .env
    image: "opennebula-frontend:${OPENNEBULA_VERSION:-latest}"
    build:
      args:
        OPENNEBULA_VERSION: "${OPENNEBULA_VERSION}"
      context: "./opennebula-frontend/${ONEDOCKER_INIT:-systemd}/"
      dockerfile: "Dockerfile-${ONEDOCKER_OS:-centos}"
    restart: always
    environment:
      OPENNEBULA_FRONTEND_SERVICE: "sunstone"
      OPENNEBULA_FRONTEND_HOSTNAME: "${OPENNEBULA_FRONTEND_HOSTNAME}"
    depends_on:
      - opennebula-frontend
    ports:
      - "9000:9869"
      - "29876:29876"
    volumes:
      - oneadmin_data:/oneadmin
    tmpfs:
      - /run
      - /run/lock
      - /tmp
      - /var/tmp
    networks:
      - onenet
    deploy:
      restart_policy:
        condition: always
        delay: 10s
      replicas: 1

  opennebula-node:
    env_file:
      - .env
    image: "opennebula-node:${OPENNEBULA_VERSION:-latest}"
    build:
      args:
        OPENNEBULA_VERSION: "${OPENNEBULA_VERSION}"
      context: "./opennebula-node/${ONEDOCKER_INIT:-systemd}/"
      #dockerfile: "Dockerfile-${ONEDOCKER_OS:-centos}"
      dockerfile: "Dockerfile-centos"
    restart: always
    privileged: true
    environment:
      OPENNEBULA_NODE_SSHPORT: "${OPENNEBULA_NODE_SSHPORT:-2222}"
      OPENNEBULA_FRONTEND_HOSTNAME: "${OPENNEBULA_FRONTEND_HOSTNAME}"
      ONEADMIN_SSH_PRIVKEY: "/ssh/id_rsa"
      ONEADMIN_SSH_PUBKEY: "/ssh/id_rsa.pub"
    volumes:
      - opennebula_nodedata:/data
      - oneadmin_nodedata:/oneadmin
      - ./ssh:/ssh:ro
    tmpfs:
      - /run
      - /run/lock
      - /tmp
      - /var/tmp
    networks:
      - onenet
    deploy:
      restart_policy:
        condition: always
        delay: 10s
      replicas: 1

