version: '3'

volumes:
  opennebula_db:
  opennebula_data:
  oneadmin_data:

networks:
  onenet:
#    external: true

services:
  db:
    env_file:
      - .env
    image: mariadb:10
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
      MYSQL_DATABASE: "${MYSQL_DATABASE}"
      MYSQL_USER: "${MYSQL_USER}"
      MYSQL_PASSWORD: "${MYSQL_PASSWORD}"
    volumes:
      - opennebula_db:/var/lib/mysql
    networks:
      - onenet
    deploy:
      restart_policy:
        condition: always
        delay: 10s
      replicas: 1

  opennebula-frontend:
    env_file:
      - .env
    image: "opennebula-frontend:${OPENNEBULA_VERSION:-latest}"
    build:
      args:
        OPENNEBULA_VERSION: "${OPENNEBULA_VERSION}"
      context: "./opennebula-frontend/${ONEDOCKER_INIT:-systemd}/"
      dockerfile: "Dockerfile-${ONEDOCKER_OS:-debian}"
    restart: always
    environment:
      OPENNEBULA_HOSTNAME: "${OPENNEBULA_HOSTNAME}"
      ONEADMIN_PASSWORD: "${ONEADMIN_PASSWORD}"
      MYSQL_DATABASE: "${MYSQL_DATABASE}"
      MYSQL_USER: "${MYSQL_USER}"
      MYSQL_PASSWORD: "${MYSQL_PASSWORD}"
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
#      ONEADMIN_SSH_PRIV_KEY: "/onedocker/sshpriv.key"
#      ONEADMIN_SSH_PUB_KEY: "/onedocker/sshpub.key"
    depends_on:
      - db
    ports:
      - "9000:9869"
    volumes:
      - opennebula_data:/data
      - oneadmin_data:/oneadmin
#      - ./identity:/onedocker/sshpriv.key:ro
#      - ./identity.pub:/onedocker/sshpub.key:ro
    tmpfs:
      - /run
      - /run/lock
      - /tmp
#      - /sys/fs/cgroup/systemd
#      - /var/lib/journal
    networks:
      - onenet
    deploy:
      restart_policy:
        condition: always
        delay: 10s
      replicas: 1

